/**
 * board-render.mjs — pure transforms for the launch board.
 *
 * No filesystem access here (the server owns I/O) so these are trivially
 * testable: move a task, render the markdown mirror, splice it into a doc.
 * All functions are immutable — they return new values, never mutate inputs.
 */

export const BOARD_START =
  '<!-- BOARD:START — auto-generated by board/server.mjs from board/tasks.json. Do not edit this section by hand. -->';
export const BOARD_END = '<!-- BOARD:END -->';

/** Throw if the board shape is unusable. Called at load time (fail fast). */
export function validateBoard(board) {
  if (!board || typeof board !== 'object') throw new Error('board must be an object');
  if (!Array.isArray(board.columns) || board.columns.length === 0)
    throw new Error('board.columns must be a non-empty array');
  if (!Array.isArray(board.tasks)) throw new Error('board.tasks must be an array');
  const columnIds = new Set(board.columns.map((c) => c.id));
  for (const task of board.tasks) {
    if (!task.id) throw new Error('every task needs an id');
    if (!columnIds.has(task.column))
      throw new Error(`task "${task.id}" has unknown column "${task.column}"`);
  }
  return board;
}

/**
 * Move one task to a column. Returns a NEW board (inputs untouched).
 * Throws if the task or column is unknown.
 */
export function applyMove(board, taskId, columnId, timestamp = null) {
  const columnIds = new Set(board.columns.map((c) => c.id));
  if (!columnIds.has(columnId)) throw new Error(`unknown column "${columnId}"`);
  if (!board.tasks.some((t) => t.id === taskId)) throw new Error(`unknown task "${taskId}"`);
  return {
    ...board,
    updatedAt: timestamp ?? board.updatedAt,
    tasks: board.tasks.map((t) => (t.id === taskId ? { ...t, column: columnId } : t)),
  };
}

function taskLine(task) {
  const done = task.column === 'done';
  const box = done ? '[x]' : '[ ]';
  const gate = task.gate ? ' ⛔ **HARD GATE**' : '';
  const ref = task.source?.ref ? ` _(${task.source.ref} — \`${task.source.file}\`)_` : '';
  const detail = task.detail ? ` — ${task.detail}` : '';
  return `- ${box} **${task.title}** · _${task.category}_${gate}${detail}${ref}`;
}

/**
 * Render the managed markdown block (markers included) that mirrors the board.
 * Columns are emitted in board order; each shows its tasks as checkbox items.
 */
export function renderMarkdownSection(board) {
  const total = board.tasks.length;
  const doneCount = board.tasks.filter((t) => t.column === 'done').length;
  const stamp = board.updatedAt ? `last updated ${board.updatedAt}` : 'no moves recorded yet';

  const lines = [];
  lines.push(BOARD_START);
  lines.push('## 🗂️ Launch board status');
  lines.push('');
  lines.push(
    `_Live mirror of the kanban board · ${stamp} · move cards in the board (\`node board/server.mjs\`) or edit \`board/tasks.json\` to change this._`,
  );
  lines.push('');
  lines.push(`**Progress: ${doneCount} / ${total} done**`);
  lines.push('');

  for (const column of board.columns) {
    const inColumn = board.tasks.filter((t) => t.column === column.id);
    lines.push(`### ${column.emoji ?? ''} ${column.name} (${inColumn.length})`.trim());
    if (inColumn.length === 0) {
      lines.push('');
      lines.push('_(none)_');
    } else {
      for (const task of inColumn) lines.push(taskLine(task));
    }
    lines.push('');
  }

  lines.push(BOARD_END);
  return lines.join('\n');
}

/**
 * Replace the managed block in `markdown` with `section`. If no block exists
 * yet, append it (with a separating rule). Returns new markdown.
 */
export function upsertSection(markdown, section) {
  const startIdx = markdown.indexOf(BOARD_START);
  const endIdx = markdown.indexOf(BOARD_END);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = markdown.slice(0, startIdx);
    const after = markdown.slice(endIdx + BOARD_END.length);
    return `${before}${section}${after}`;
  }
  const trimmed = markdown.replace(/\s+$/, '');
  return `${trimmed}\n\n---\n\n${section}\n`;
}
